# Generated by Django 3.0.5 on 2021-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy_loading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
